[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Lily Richards <lilymichellerichards@gmail.com>"]
edition = "2021"

[workspace.dependencies]
petgraph = "0.6.4"
priority-queue = "1.3.2"
threadpool = "1.8.1"
